@token = ...
#@token = {{$aadV2Token scopes:https://jelledruyts.onmicrosoft.com/authproxytestwebapp/identity.read tenantid:jelledruyts.onmicrosoft.com clientid:fb859816-0967-41eb-a59f-6a525d3fda8e}}

###

GET https://localhost:7268/api/identity
Authorization: Bearer {{token}}

###

POST https://localhost:7268/api/token
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "profile": "UserCallsGraph"
}

###

POST https://localhost:7268/api/forwardcall?destinationUrl=https://graph.microsoft.com/v1.0/me
Authorization: Bearer {{token}}