@token = ...
#@token = {{$aadV2Token scopes:https://identitysamples.onmicrosoft.com/authproxytestwebapp/identity.read tenantid:identitysamples.onmicrosoft.com clientid:afb67e6a-e8c5-4a76-9a89-03d37da45f72}}

###

GET https://localhost:7268/api/identity
Authorization: Bearer {{token}}

###

POST https://localhost:7268/api/token
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "profile": "UserCallsGraph"
}

###

POST https://localhost:7268/api/forwardcall?destinationUrl=https://graph.microsoft.com/v1.0/me
Authorization: Bearer {{token}}